var mongoose = require('mongoose');

var Schema = mongoose.Schema;

var CVInfoSchema = new Schema(
    {
        userID: { type: Number, required: true }, // generated by database
        userInfo: { type: Schema.Types.ObjectId, ref: "UserInfo", required: true },
        description: { type: String, required: true },
        skills: [{ type: Schema.Types.ObjectId, ref: "Skill" }],
        languages: [{ type: Schema.Types.ObjectId, ref: "Skill" }],
        operatingSystems: [{ type: Schema.Types.ObjectId, ref: "Skill" }],
        otherSkills: [{ type: String }],
        experience: [{ type: Schema.Types.ObjectId, ref: "Work" }],
    }
)

CVInfoSchema.virtual("url").get(function () {
    return "/users/user/" + this._id;
});

module.exports = mongoose.model("CVInfo", CVInfoSchema);